# Generated by Django 4.2.7 on 2025-04-27 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_user_age_user_gender"),
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_profile",
                to="student.user",
            ),
        ),
        migrations.DeleteModel(name="User",),
    ]
